---

- name: Download Logstash RPM package
  uri:
    url: "{{ logstash_rpm_url | default('https://artifacts.elastic.co/downloads/logstash/logstash-5.3.3.rpm') }}"
    dest: "{{ rpm_download_directory | default('/var/cache/yum/x86_64/7/extras/packages') }}"

- name: Install Logstash
  yum: 
    name: "{{ rpm_download_directory | default('/var/cache/yum/x86_64/7/extras/packages') }}/{{ logstash_rpm_package | default('logstash-5.3.3.rpm') }}"
    state: installed
  register: rpm_installation

# Logstash configuration
- include: config.yml
  
- name: Start Logstash
  service: 
    name: logstash 
    state: restarted
    enabled: yes
  ignore_errors: true
