---
#
# Playbook to install the ELK stack + Beats
#
- hosts: elkservers
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
  - { role: java }
  - { role: elasticsearch }
  - { role: kibana }
  - { role: metricbeat }
  - { role: logstash }
